import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript
import { throwErrorMiddleware } from "./middleware";


export const ApiBaseUrl = () => import.meta.env.VITE_SERVER_URL
    || (() => { throw new Error("VITE_SERVER_URL is not defined. Check your environment variables."); })();

export const OpenApiSpecUrl = () => import.meta.env.VITE_OPENAPI_SPEC_URL
    || (() => { throw new Error("VITE_OPENAPI_SPEC_URL is not defined. Check your environment variables."); })();





const getFetchClient = () => {
    const client = createFetchClient<paths>({
        baseUrl: ApiBaseUrl(),
        headers: {
            "Authorization": `Bearer ${localStorage.getItem("accessToken")}`, // Use the access token if available
        },
    });
    client.use(throwErrorMiddleware); // Uncomment if you have an error handling middleware

    return client;
};


export const $fetchClient = getFetchClient();
export const $queryClient = createClient($fetchClient);

