name: Docker Release AMD64

on:
  push:
    #branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    #branches: [ "master" ]

jobs:

  build:
    if: github.ref_type == 'tag'
    name: Build OllamaFarmer
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write

    steps:
    - uses: actions/checkout@v4
      name: Git Checkout
      
    - name: Set Build Version
      id: build_version
      run: echo "result=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        flavor: |
          latest=true
        tags: |
          type=semver,event=tag,pattern={{major}}.{{minor}}.{{patch}}
        images: merrrp/ollama-farmer
        labels: |
          type=ref,event=branch
          type=ref,event=tag
        

    - name: Build OllamaFarmer AMD64
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: BUILD_VERSION=${{ steps.build_version.outputs.result }}
        platforms: linux/amd64
        push: ${{ github.ref_type == 'tag' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: OllamaFarmer.Server/Dockerfile

    - name: Docker Scout
      if: github.ref_type == 'tag'
      uses: docker/scout-action@v1
      with:
        command: cves
        image: merrrp/ollama-farmer:${{ steps.build_version.outputs.result }}
        sarif-file: sarif.output.json
        summary: true

    - name: Upload SARIF result
      id: upload-sarif
      if: github.ref_type == 'tag'
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: sarif.output.json

    - name: Generate Release Notes
      id: release_notes
      if: github.ref_type == 'tag'
      run: |
        # Extract version from tag (remove 'v' prefix)
        VERSION="${GITHUB_REF_NAME#v}"
        
        # Create release notes
        cat > release_notes.md << EOF
        ## 🚀 OllamaFarmer v${VERSION}
        
        ### Docker Images
        - \`merrrp/ollama-farmer:${VERSION}\`
        - \`merrrp/ollama-farmer:latest\`
        
        ### What's New
        This release includes the latest features and improvements to OllamaFarmer.
        
        ### Installation
        \`\`\`bash
        # Using Docker
        docker run -p 8080:8080 merrrp/ollama-farmer:${VERSION}
        
        # Using Docker Compose
        # See README.md for complete setup instructions
        \`\`\`
        
        ### Security
        ✅ Docker image has been scanned for vulnerabilities
        
        ---
        
        **Full Changelog**: https://github.com/Merp4/OllamaFarmer/compare/v${VERSION}...v${VERSION}
        EOF

    - name: Create GitHub Release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      with:
        name: OllamaFarmer ${{ steps.build_version.outputs.result }}
        body_path: release_notes.md
        draft: false
        prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'rc') }}
        generate_release_notes: true
              
