name: Docker PR AMD64

on:
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  build:
    if: ${{ github.event_name == 'pull_request' }}
    env:
        COMPARE_TAG: pr-${{ github.base_ref }}
        VERSION_TAG: pr-${{ github.base_ref }}-${{ github.event.pull_request.number }}
        VERSION: 0.0.${{ github.run_number }}.${{ github.run_attempt }}
    name: Build OllamaFarmer
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for the docker/scout-action to read the repository contents
      pull-requests: write # Required for the docker/scout-action to write comments on PRs

    steps:
    - uses: actions/checkout@v4
      name: Git Checkout
      
      
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: merrrp/ollama-farmer
        flavor: |
          latest=false
        tags: |
          type=raw,value=${{ env.VERSION_TAG }}

    - name: Build OllamaFarmer
      uses: docker/build-push-action@v5
      with:
        context: .
        build-args: BUILD_VERSION=${{ env.VERSION }}
        platforms: linux/amd64
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: OllamaFarmer.Server/Dockerfile
              


    - name: Docker Scout
      id: docker-scout
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker/scout-action@v1
      with:
        command: cves
        image: ${{ steps.meta.outputs.tags }}
        only-severities: critical,high
        write-comment: true
        github-token: ${{ secrets.GITHUB_TOKEN }} # to be able to write the comment